[tool.poetry]
name = "pythontest"
version = "0.1.0"
description = ""
authors = ["HarithaVattikuti <73516759+HarithaVattikuti@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
python101 = "^0.0.1"
build = "^1.2.1"
cffi = "^1.15.1"  # Add this line


[tool.poetry-dynamic-versioning.substitution]
folders = [{ path = "." }]
patterns = [
  "(^__version__\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
  "(^release\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
  { value = "(^__version_tuple__\\s*(?::.*?)?=\\s*\\()[^)]*(\\))", mode = "tuple" },
]

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "pragma: no cover",
  "raise NotImplementedError"
]
fail_under = 100
omit = [
  "**/tm_devices/commands/**"  # TODO: remove this exclusion
]
show_missing = true
skip_empty = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
