name: Validate SHA256 Hash

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download file
        run: wget https://github.com/actions/python-versions/releases/download/3.10.14-9004012336/hashes.sha256

      - name: Validate SHA256 Hashes
        run: shasum -a 256 -c hashes.sha256
