name: Validate SHA256 Hash

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download file
        run: wget https://github.com/HarithaVattikuti/python-versions/releases/download/3.13.0-beta.2-9452565873/hashes.sha256

      - name: Validate SHA256 Hashes
        run: shasum -a 256 -c hashes.sha256
