name: multiple cache save

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  save-cache:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Create File
        run: |
          mkdir -p Reports
          cd Reports
          echo "Operating System is "${{ inputs.os }} >> ${{ inputs.os }}.txt
          cd ..
          ls
          cat Reports/${{ inputs.os }}.txt
     
      - name: Cache dependencies
        uses: actions/cache/save@v4
        with:
          path: Reports
          key: ${{ github.run_id }}-report
      
