name: Multiple cache restore

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  restore-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: Reports
          key: ${{ github.run_id }}-report
          
