name: Calling workflow

on:
  workflow_dispatch:
  
jobs:
  call-reusable:
    uses: HarithaVattikuti/java-test/.github/workflows/reusable1.yml@reusable-patch
    secrets:
      token: ${{ secrets.PAT }}
