name: Parent Workflow

on: 
  workflow_dispatch:

jobs:
  call-workflow1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/multiplecachesave.yml
    with:
      os: ${{ matrix.os }}
            
  call-workflow2:
    needs: call-workflow1
    uses: ./.github/workflows/MultipleCacheRestore.yml
    with:
      os: ${{ matrix.os }}

