name: Run PowerShell Script

on: 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Which python3
        run: which python3

      - name: Real path of python3
        run: readlink -f $(which python3)

      - name: Find all tool cache Python bins
        run: find /opt/hostedtoolcache/Python/ -type d -name bin

      - name: Python3 executable from Python
        run: python3 -c "import sys; print(sys.executable)"
