name: Test Python Location 

on:
  workflow_dispatch:

jobs:
  positivetestcases:
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
          runners: ['ubuntu-latest','windows-latest','macos-13','macos-latest']
          python-version: [ '3.11', 'pypy3.10', 'graalpy-24.0', '3.13t' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up ${{ matrix.python-implementation }} ${{ matrix.python-version }}
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check pythonLocation variable
        run: |
          echo "pythonLocation: $pythonLocation"
          if [[ -z "$pythonLocation" ]]; then
            echo "::error ::pythonLocation is not set"
            exit 1
          fi
          # Optionally, check that pythonLocation points to a valid Python binary
          "$pythonLocation/bin/python" --version

  negativetestcases:
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
          runners: ['ubuntu-latest','windows-latest','macos-13','macos-latest']
          python-version: [ '3.11', 'pypy3.12', 'graalpy-24.0', 'invalid' ]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up ${{ matrix.python-implementation }} ${{ matrix.python-version }}
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}
        continue-on-error: true
      - name: Assert action failed as expected
        run: |
          if [ $? -eq 0 ]; then
            echo "::error ::Action should have failed but did not."
            exit 1
          else
            echo "Failure as expected for invalid config."
          fi
