name: Reusable workflow example

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
    

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use tags
      run: |
          echo "Tags: ${{ inputs.tags }}"
