name: Test pip file

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04] #, ubuntu-22.04-arm, macos-13, ubuntu-latest, ubuntu-24.04-arm]
        python-version: [3.13.2, 3.13t, 3.14t-dev]
    steps:
    - uses: actions/checkout@v4
    - name: build-version-file
      run: echo "" > Pipfile
    - uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
      with:
        #python-version: ${{ matrix.python-version }}
        python-version-file: Pipfile

  buildonpipfile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04] #, ubuntu-22.04-arm, macos-13, ubuntu-latest, ubuntu-24.04-arm]
        python-version: [3.13.2, 3.13t, 3.14t-dev]
    steps:
    - uses: actions/checkout@v4
    - name: build-version-file ${{ matrix.python-version }}
      run: |
        echo '[requires]
        python_full_version = "${{ matrix.python-version }}"
        ' > Pipfile
    - uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
      with:
        #python-version: ${{ matrix.python-version }}
        python-version-file: Pipfile
