name: tests 3.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
        - uses: actions/checkout@v6
        - name: test 3.8
          uses: actions/setup-python@v6
          with:
            python-version: "3.8"
