name: Test pypy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-22.04, macos-13, ubuntu-latest ]
        python-version:
        - 'pypy3.7' # the latest available version of PyPy that supports Python 3.7
        - 'pypy3.7-v7.3.3' # Python 3.7 and PyPy 7.3.3
        - 'graalpy-24.0'
        - 'pypy3.10'
        - '3.12'
        - 'pypy-3.9'
        - 'pypy-2.7'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

  setup-versions-from-tool-versions-file:
    name: Setup ${{ matrix.python }} ${{ matrix.os }} .tool-versions file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-22.04, macos-13, ubuntu-latest ]
        python: [3.13, 3.13.1t, pypy3.9-nightly, pypy3.11-7.3.18, graalpy-24.1.2, pypy3.10-v7.3.12rc1]
        exclude:
          - os: windows-latest
            python: graalpy-24.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build-tool-versions-file ${{ matrix.python }}
        run: |
          echo "python ${{ matrix.python }}" > .tool-versions
      - name: setup-python using .tool-versions ${{ matrix.python }}
        id: setup-python-tool-versions
        uses: mahabaleshwars/setup-python@feature/tool-versions-file-support
        with:
          python-version-file: .tool-versions
