name: Test version on Macos Latest

on:
  workflow_dispatch:

jobs:
  buildv6:
    name: Test on v6
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest , macos-15-intel]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    
    steps:
        - uses: actions/checkout@v6

        - name: Set up Python using v5
          uses: actions/setup-python@v6
          with:
              python-version: ${{ matrix.python-version }}
