name: Test Alpha Python Versions

on:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, Windows, macOS]
        python_version: ["3.14"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          allow-prereleases: true
      - run: pipx run nox --error-on-missing-interpreters -s tests-${{ matrix.python_version }}
      
  test-freethreaded:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version:
          - '3.13.0-beta.4'
          - '3.13.0-rc.1'
          - '3.14.0-alpha.4'
          - '3.14t-dev'

          
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
          freethreaded: true

