name: Validate Python Prerelease

on:
  workflow_dispatch:

jobs:
  setup-dev-version:
    name: Setup 3.14-dev ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-python 3.14-dev
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14-dev'

      #- name: Check python-path
     #   run: ./__tests__/check-python-path.sh '${{ steps.setup-python.outputs.python-path }}'
      #  shell: bash

      - name: Validate version
        run: ${{ startsWith(steps.setup-python.outputs.python-version, '3.14.') }}
        shell: bash

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-prerelease-version:
    name: Setup 3.14 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-python 3.14
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          allow-prereleases: true

#      - name: Check python-path
 #       run: ./__tests__/check-python-path.sh '${{ steps.setup-python.outputs.python-path }}'
 #       shell: bash

      - name: Validate version
        run: ${{ startsWith(steps.setup-python.outputs.python-version, '3.14.') }}
        shell: bash

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'
