name: Testing Pip install
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13,windows-11-arm,ubuntu-22.04-arm]       
    steps:
      - name: Checkout code
        uses: actions/checkout@v5 
        
      - name: Remove WindowsApps from PATH
        if: runner.os == 'Windows'     
        shell: pwsh
        run: |
          $newPath = $env:PATH -replace [regex]::Escape('C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps;'), ''
          echo "PATH=$newPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append            
      - name: Set up python
        uses: gowridurgad/setup-python@pip-install
        with:
      
            python-version:  '3.13t'
            cache: pip
            cache-dependency-path: requirements.txt 
            pip-install: -r requirements.txt 
