name: Test Python Tk
on:
  workflow_dispatch:

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-13]
        python-version: ["3.8.18","3.10.16","3.9.21","3.12.8"]
      fail-fast: false
    name: ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: HarithaVattikuti/setup-python@testtkinter
        with:
          python-version: ${{ matrix.python-version }}

      # - name: check tkinter
      #   run: python3 -c "import tkinter; print(tkinter.TkVersion)"
     
      # - name: Install Tkinter
      #   run: brew install python-tk@3.12
      
      # - name: check tkinter
      #   run: python3 -c "import tkinter; print(tkinter.TkVersion)"
     
      # - name: Set environment variables for Tkinter
      #   run: |
      #     echo "TK_LIBRARY=$(brew --prefix tcl-tk)/lib" >> $GITHUB_ENV
      #     echo "TCL_LIBRARY=$(brew --prefix tcl-tk)/lib" >> $GITHUB_ENV
      #     echo "PYTHON_CONFIGURE_OPTS='--with-tcltk-includes=\"-I$(brew --prefix tcl-tk)/include\" --with-tcltk-libs=\"-L$(brew --prefix tcl-tk)/lib -ltcl8.6 -ltk8.6\" --enable-shared'" >> $GITHUB_ENV

      # - name: Install Python dependencies
      #   run: |
      #     python -m ensurepip
      #     python -m pip install --upgrade pip
          
      - name: Run tk script
        run: python tk_min.py
