name: Test Python Tk
on:
  workflow_dispatch:

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-13, macos-latest]
        python-version: ["3.10.10", "3.10.11", "3.11.9"]
      fail-fast: false
    name: ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: UnInstall Tkinter
        run: brew uninstall python-tk

      - name: Install Tkinter
        run: brew install python-tk
        
      - name: Run tk script
        run: python tk_min.py
