name: Test schedule tag

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * 1-5"
    - cron: "*/6 * * * *"

jobs:
  scheduleJobs1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - schedule: "*/5 * * * 1-5"
            tag: "@tag1"
          - schedule: "*/6 * * * *"
            tag: "@tag2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run reusable job
        if: ${{ matrix.config.schedule == github.event.schedule }}
        uses: ./.github/workflows/ReusableJob.yml
        with:
          tags: ${{ matrix.config.tag }}

  scheduleJobs2:
    strategy:
      fail-fast: false
      matrix:
        config:
          - schedule: "*/5 * * * 1-5"
            tag: "@tag1"
          - schedule: "*/6 * * * *"
            tag: "@tag2"
          
    if: github.event.schedule == '*/6 * * * *'
    uses: ./.github/workflows/ReusableJob.yml
    with:
      tags: ${{matrix.config.tag}}
