name: Validate Python Prerelease

on:
  workflow_dispatch:

jobs:
  

  setup-prerelease-version:
    name: Setup 3.15 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: setup-python 3.15
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.15'
          allow-prereleases: true

#      - name: Check python-path
 #       run: ./__tests__/check-python-path.sh '${{ steps.setup-python.outputs.python-path }}'
 #       shell: bash

      - name: Validate version
        run: ${{ startsWith(steps.setup-python.outputs.python-version, '3.15.') }}
        shell: bash

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'
